function SaveMasks(masks, saveFile)

    % SaveMasksToCSV saves the coordinates of each mask to a .csv file.
    %
    % Inputs:
    %        masks    : Struct containing masks generated by makeChartMask.
    %        saveFile : File path to save the mask coordinates as  
    %                   a .csv file.



    % Open a file for writing
    fid = fopen(saveFile, 'w');
    if fid == -1
        error('Could not open file %s for writing.', saveFile);
    end

    % Write the header
    fprintf(fid, 'x,y\n');

    % Loop through each mask and extract coordinates
    maskNames = fieldnames(masks);
    for i = 1:numel(maskNames)
        maskName = maskNames{i};
        coordinates = masks.(maskName).pts; % Extract the coordinates (Nx2 array)

        % Write each coordinate to the file
        for j = 1:size(coordinates, 1)
            fprintf(fid, '%.6f,%.6f\n', coordinates(j, 1), coordinates(j, 2));
        end
    end

    % Close the file
    fclose(fid);

    % Display confirmation
    fprintf('Mask coordinates saved to %s\n', saveFile);
end
